server:
  port: 20000
spring:
  application:
    name: gateway-simple
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.90:8848
    gateway:
      discovery:
        locator: # 定位器
          enabled: true # 开启注册中心路由功能
#========================================配置1：固定地址========================================
#      routes:
#        - id: test-2001
#          uri: http://localhost:19999 # 指定地址
#          predicates: # 断言
#            - Path=/api/** #断言，路径相匹配进行路由
#========================================配置2：负载均衡地址========================================
#      routes:
#        - id: test-2001
#          uri: lb://ms-workflow-example # 通过命名空间 负载均衡
#          predicates: # 断言
#            - Path=/api/** #断言，路径相匹配进行路由
#========================================配置3：断言========================================
#      routes:
#        - id: test-2001
#          uri: lb://ms-workflow-example # 通过命名空间 负载均衡
#          predicates: # 断言
#            - Path=/api/** #断言，路径相匹配进行路由
##            - After=2023-06-02T16:53:36.467+08:00[Asia/Shanghai]
##            - Cookie=username,[a-z]+ # 匹配Cookie的key和value(正则表达式)
##            - Header=X-Request-Id, \d+ #表示数字
##            - Host=**.msb.com # 匹配当前的主机地址发出的请求
##            - Method=Post # 匹配请求方法，逗号隔开
##            - Query=taskInstId,.+ # 匹配请求参数
##            - Weight=group1, 8
#========================================配置4：filter========================================
      routes:
        - id: test-2001
          uri: lb://ms-workflow-example # 通过命名空间 负载均衡
          predicates: # 断言
            - Path=/msb/api/** #断言，路径相匹配进行路由
          filters:
            - StripPrefix=1 # 去掉地址中的第一部分